import type { AuthConfig } from './config'

export interface ServiceTemplate {
  id: string
  name: string
  description: string
  defaultSlug: string
  /** Path under specs/ to the bundled OpenAPI spec */
  bundledSpec: string
  /** Optional public path prefix before API paths */
  publicPathPrefix?: string
  /** Optional versioned spec list when a product's API changes by release */
  specVersions?: Array<{
    value: string
    bundledSpec: string
  }>
  /** Default auth config (user fills in the secret) */
  authType: AuthConfig['type']
  /** For 'header' auth: the header name */
  authHeaderName?: string
  /** For 'header' auth: a scheme word the API expects before the secret, e.g. `token ` for Gitea. */
  authValuePrefix?: string
  /** Placeholder for the URL input */
  urlPlaceholder: string
  /** Label for the token/secret input */
  tokenLabel: string
  /** URL to logo image */
  logo: string
  /** Brand color hex */
  color: string
  /** Endpoint to test connectivity (relative to base URL) */
  testEndpoint: string
}

export const templates: ServiceTemplate[] = [
  {
    id: 'sonarr',
    name: 'Sonarr',
    description: 'TV show management',
    defaultSlug: 'sonarr',
    bundledSpec: 'sonarr.json',
    authType: 'header',
    authHeaderName: 'X-Api-Key',
    urlPlaceholder: 'http://sonarr:8989',
    tokenLabel: 'API Key',
    logo: 'https://raw.githubusercontent.com/Sonarr/Sonarr/develop/Logo/Sonarr.svg',
    color: '#35c5f4',
    testEndpoint: '/api/v3/system/status',
  },
  {
    id: 'radarr',
    name: 'Radarr',
    description: 'Movie management',
    defaultSlug: 'radarr',
    bundledSpec: 'radarr.json',
    authType: 'header',
    authHeaderName: 'X-Api-Key',
    urlPlaceholder: 'http://radarr:7878',
    tokenLabel: 'API Key',
    logo: 'https://raw.githubusercontent.com/Radarr/Radarr/develop/Logo/Radarr.svg',
    color: '#ffc230',
    testEndpoint: '/api/v3/system/status',
  },
  {
    id: 'prowlarr',
    name: 'Prowlarr',
    description: 'Indexer manager',
    defaultSlug: 'prowlarr',
    bundledSpec: 'prowlarr.json',
    authType: 'header',
    authHeaderName: 'X-Api-Key',
    urlPlaceholder: 'http://prowlarr:9696',
    tokenLabel: 'API Key',
    logo: 'https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/Prowlarr.svg',
    color: '#c4a41a',
    testEndpoint: '/api/v1/system/status',
  },
  {
    id: 'lidarr',
    name: 'Lidarr',
    description: 'Music management',
    defaultSlug: 'lidarr',
    bundledSpec: 'lidarr.json',
    authType: 'header',
    authHeaderName: 'X-Api-Key',
    urlPlaceholder: 'http://lidarr:8686',
    tokenLabel: 'API Key',
    logo: 'https://raw.githubusercontent.com/Lidarr/Lidarr/develop/Logo/Lidarr.svg',
    color: '#00bc8c',
    testEndpoint: '/api/v1/system/status',
  },
  {
    id: 'jellyfin',
    name: 'Jellyfin',
    description: 'Media server',
    defaultSlug: 'jellyfin',
    bundledSpec: 'jellyfin/12.0.0.json',
    // 12.0 removed endpoints (HLS, ActiveEncodings, …) that 10.11 servers still serve.
    specVersions: [
      { value: '12.0.0', bundledSpec: 'jellyfin/12.0.0.json' },
      { value: '10.11.11', bundledSpec: 'jellyfin/10.11.11.json' },
    ],
    authType: 'header',
    authHeaderName: 'X-Emby-Token',
    urlPlaceholder: 'http://jellyfin:8096',
    tokenLabel: 'API Key',
    logo: 'https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-transparent.svg',
    color: '#00a4dc',
    testEndpoint: '/System/Info',
  },
  {
    id: 'seerr',
    name: 'Seerr',
    description: 'Media requests',
    defaultSlug: 'seerr',
    bundledSpec: 'seerr.json',
    authType: 'header',
    authHeaderName: 'X-Api-Key',
    urlPlaceholder: 'http://seerr:5055',
    tokenLabel: 'API Key',
    logo: 'https://raw.githubusercontent.com/seerr-team/seerr/develop/public/os_icon.svg',
    color: '#7b2fef',
    testEndpoint: '/api/v1/settings/main',
  },
  {
    id: 'immich',
    name: 'Immich',
    description: 'Photo management',
    defaultSlug: 'immich',
    bundledSpec: 'immich.json',
    // 3.0 removed endpoints 2.x servers still serve (/sync/full-sync, /assets/random, …).
    specVersions: [
      { value: 'latest (3.x)', bundledSpec: 'immich.json' },
      { value: '2.0.0', bundledSpec: 'immich/2.0.0.json' },
    ],
    authType: 'header',
    authHeaderName: 'x-api-key',
    urlPlaceholder: 'http://immich:2283',
    tokenLabel: 'API Key',
    logo: 'https://raw.githubusercontent.com/immich-app/immich/main/docs/static/img/immich-logo.svg',
    color: '#4250af',
    testEndpoint: '/api/users/me',
  },
  {
    id: 'portainer',
    name: 'Portainer',
    description: 'Container management',
    defaultSlug: 'portainer',
    bundledSpec: 'portainer.json',
    authType: 'header',
    authHeaderName: 'X-API-Key',
    urlPlaceholder: 'http://portainer:9000',
    tokenLabel: 'API Key',
    logo: 'https://raw.githubusercontent.com/portainer/portainer/develop/app/assets/images/logo_alt.svg',
    color: '#13bef9',
    testEndpoint: '/api/endpoints',
  },
  {
    id: 'bazarr',
    name: 'Bazarr',
    description: 'Subtitle management',
    defaultSlug: 'bazarr',
    bundledSpec: 'bazarr.json',
    authType: 'header',
    authHeaderName: 'X-API-KEY',
    urlPlaceholder: 'http://bazarr:6767',
    tokenLabel: 'API Key',
    logo: 'https://raw.githubusercontent.com/morpheus65535/bazarr/master/frontend/public/images/logo128.png',
    color: '#2ea44f',
    testEndpoint: '/api/system/status',
  },
  {
    id: 'unifi-network',
    name: 'UniFi Network',
    description: 'UniFi network controller',
    defaultSlug: 'unifi-network',
    bundledSpec: 'unifi-network/10.6.101.json',
    publicPathPrefix: '/proxy/network',
    specVersions: [
      { value: '10.6.101', bundledSpec: 'unifi-network/10.6.101.json' },
      { value: '10.5.67', bundledSpec: 'unifi-network/10.5.67.json' },
      { value: '10.5.62', bundledSpec: 'unifi-network/10.5.62.json' },
      { value: '10.4.57', bundledSpec: 'unifi-network/10.4.57.json' },
      { value: '10.4.55', bundledSpec: 'unifi-network/10.4.55.json' },
      { value: '10.4.46', bundledSpec: 'unifi-network/10.4.46.json' },
      { value: '10.3.58', bundledSpec: 'unifi-network/10.3.58.json' },
      { value: '10.3.47', bundledSpec: 'unifi-network/10.3.47.json' },
      { value: '10.2.105', bundledSpec: 'unifi-network/10.2.105.json' },
      { value: '10.2.104', bundledSpec: 'unifi-network/10.2.104.json' },
      { value: '10.2.97', bundledSpec: 'unifi-network/10.2.97.json' },
      { value: '10.2.93', bundledSpec: 'unifi-network/10.2.93.json' },
    ],
    authType: 'header',
    authHeaderName: 'X-API-KEY',
    urlPlaceholder: 'https://unifi-controller.example.com',
    tokenLabel: 'API Key',
    logo: 'https://cdn.simpleicons.org/ubiquiti/0559C9',
    color: '#0559c9',
    testEndpoint: '/integration/v1/info',
  },
  {
    id: 'unifi-protect',
    name: 'UniFi Protect',
    description: 'UniFi camera and NVR management',
    defaultSlug: 'unifi-protect',
    bundledSpec: 'unifi-protect/7.2.105.json',
    publicPathPrefix: '/proxy/protect',
    specVersions: [
      { value: '7.2.105', bundledSpec: 'unifi-protect/7.2.105.json' },
      { value: '7.1.87', bundledSpec: 'unifi-protect/7.1.87.json' },
      { value: '7.1.83', bundledSpec: 'unifi-protect/7.1.83.json' },
      { value: '7.1.77', bundledSpec: 'unifi-protect/7.1.77.json' },
      { value: '7.1.76', bundledSpec: 'unifi-protect/7.1.76.json' },
      { value: '7.1.75', bundledSpec: 'unifi-protect/7.1.75.json' },
      { value: '7.1.60', bundledSpec: 'unifi-protect/7.1.60.json' },
      { value: '7.0.107', bundledSpec: 'unifi-protect/7.0.107.json' },
      { value: '7.0.106', bundledSpec: 'unifi-protect/7.0.106.json' },
      { value: '7.0.104', bundledSpec: 'unifi-protect/7.0.104.json' },
      { value: '7.0.94', bundledSpec: 'unifi-protect/7.0.94.json' },
      { value: '7.0.88', bundledSpec: 'unifi-protect/7.0.88.json' },
      { value: '7.0.85', bundledSpec: 'unifi-protect/7.0.85.json' },
    ],
    authType: 'header',
    authHeaderName: 'X-API-KEY',
    urlPlaceholder: 'https://unifi-protect.example.com',
    tokenLabel: 'API Key',
    logo: 'https://cdn.simpleicons.org/ubiquiti/0559C9',
    color: '#0b7cff',
    testEndpoint: '/integration/v1/meta/info',
  },
  {
    id: 'komga',
    name: 'Komga',
    description: 'Comic and manga server',
    defaultSlug: 'komga',
    bundledSpec: 'komga.json',
    authType: 'header',
    authHeaderName: 'X-API-Key',
    urlPlaceholder: 'http://komga:25600',
    tokenLabel: 'API Key',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/komga.svg',
    color: '#0E7C7B',
    testEndpoint: '/api/v2/users/me',
  },
  {
    id: 'kavita',
    name: 'Kavita',
    description: 'Reading and manga server',
    defaultSlug: 'kavita',
    bundledSpec: 'kavita/0.9.1.4.json',
    specVersions: [
      { value: '0.9.1.4', bundledSpec: 'kavita/0.9.1.4.json' },
      { value: '0.8.6', bundledSpec: 'kavita/0.8.6.json' },
      { value: '0.7.14', bundledSpec: 'kavita/0.7.14.json' },
    ],
    authType: 'header',
    authHeaderName: 'x-api-key',
    urlPlaceholder: 'http://kavita:5000',
    tokenLabel: 'API Key',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/kavita.svg',
    color: '#4AC694',
    testEndpoint: '/api/Health',
  },
  {
    id: 'audiobookshelf',
    name: 'Audiobookshelf',
    description: 'Audiobook and podcast server',
    defaultSlug: 'audiobookshelf',
    bundledSpec: 'audiobookshelf.json',
    authType: 'bearer',
    urlPlaceholder: 'http://audiobookshelf:13378',
    tokenLabel: 'API Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/audiobookshelf.svg',
    color: '#FAA307',
    testEndpoint: '/api/libraries',
  },
  {
    id: 'karakeep',
    name: 'Karakeep',
    description: 'Bookmark and read-it-later',
    defaultSlug: 'karakeep',
    bundledSpec: 'karakeep.json',
    authType: 'bearer',
    urlPlaceholder: 'http://karakeep:3000',
    tokenLabel: 'API Key',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/karakeep.svg',
    color: '#3B82F6',
    testEndpoint: '/api/v1/users/me',
  },
  {
    id: 'gotify',
    name: 'Gotify',
    description: 'Push notifications',
    defaultSlug: 'gotify',
    bundledSpec: 'gotify.json',
    authType: 'header',
    authHeaderName: 'X-Gotify-Key',
    urlPlaceholder: 'http://gotify:80',
    tokenLabel: 'Client Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/gotify.svg',
    color: '#1B72BE',
    testEndpoint: '/current/user',
  },
  {
    id: 'photoprism',
    name: 'PhotoPrism',
    description: 'Photo management',
    defaultSlug: 'photoprism',
    bundledSpec: 'photoprism.json',
    authType: 'bearer',
    urlPlaceholder: 'http://photoprism:2342',
    tokenLabel: 'App Password',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/photoprism.svg',
    color: '#00A9CE',
    testEndpoint: '/api/v1/config',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    description: 'Dashboards and observability',
    defaultSlug: 'grafana',
    bundledSpec: 'grafana/13.2.1.json',
    specVersions: [
      { value: '13.2.1', bundledSpec: 'grafana/13.2.1.json' },
      { value: '12.0.0', bundledSpec: 'grafana/12.0.0.json' },
      { value: '11.0.0', bundledSpec: 'grafana/11.0.0.json' },
    ],
    authType: 'bearer',
    urlPlaceholder: 'http://grafana:3000',
    tokenLabel: 'Service Account Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/grafana.svg',
    color: '#F46800',
    testEndpoint: '/api/org',
  },
  {
    id: 'netdata',
    name: 'Netdata',
    description: 'Real-time system monitoring',
    defaultSlug: 'netdata',
    bundledSpec: 'netdata.json',
    authType: 'none',
    urlPlaceholder: 'http://netdata:19999',
    tokenLabel: 'Bearer Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/netdata.svg',
    color: '#00AB44',
    testEndpoint: '/api/v1/info',
  },
  {
    id: 'semaphore',
    name: 'Semaphore',
    description: 'Ansible and Terraform UI',
    defaultSlug: 'semaphore',
    bundledSpec: 'semaphore.json',
    authType: 'bearer',
    urlPlaceholder: 'http://semaphore:3000',
    tokenLabel: 'API Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/semaphore.svg',
    color: '#3F51B5',
    testEndpoint: '/api/user/',
  },
  {
    id: 'vikunja',
    name: 'Vikunja',
    description: 'Tasks and projects',
    defaultSlug: 'vikunja',
    bundledSpec: 'vikunja.json',
    authType: 'bearer',
    urlPlaceholder: 'http://vikunja:3456',
    tokenLabel: 'API Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/vikunja.svg',
    color: '#1973FF',
    testEndpoint: '/api/v1/user',
  },
  {
    id: 'homebox',
    name: 'Homebox',
    description: 'Home inventory',
    defaultSlug: 'homebox',
    bundledSpec: 'homebox.json',
    authType: 'bearer',
    urlPlaceholder: 'http://homebox:7745',
    tokenLabel: 'API Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/homebox.svg',
    color: '#4F8A8B',
    testEndpoint: '/api/v1/users/self',
  },
  {
    id: 'headscale',
    name: 'Headscale',
    description: 'Self-hosted Tailscale control',
    defaultSlug: 'headscale',
    bundledSpec: 'headscale.json',
    authType: 'bearer',
    urlPlaceholder: 'http://headscale:8080',
    tokenLabel: 'API Key',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/headscale.svg',
    color: '#5C6AC4',
    testEndpoint: '/api/v1/apikey',
  },
  {
    id: 'mailcow',
    name: 'mailcow',
    description: 'Mail server suite',
    defaultSlug: 'mailcow',
    bundledSpec: 'mailcow.json',
    authType: 'header',
    authHeaderName: 'X-API-Key',
    urlPlaceholder: 'https://mail.example.com',
    tokenLabel: 'API Key',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/mailcow.svg',
    color: '#16A0C8',
    testEndpoint: '/api/v1/get/status/version',
  },
  {
    id: 'jellystat',
    name: 'Jellystat',
    description: 'Jellyfin statistics',
    defaultSlug: 'jellystat',
    bundledSpec: 'jellystat.json',
    authType: 'header',
    authHeaderName: 'x-api-token',
    urlPlaceholder: 'http://jellystat:3000',
    tokenLabel: 'API Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/jellystat.svg',
    color: '#6B46C1',
    testEndpoint: '/api/getLibraries',
  },
  {
    id: 'changedetection',
    name: 'changedetection.io',
    description: 'Website change monitoring',
    defaultSlug: 'changedetection',
    bundledSpec: 'changedetection.json',
    authType: 'header',
    authHeaderName: 'x-api-key',
    urlPlaceholder: 'http://changedetection:5000',
    tokenLabel: 'API Key',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/changedetection.svg',
    color: '#0A9396',
    testEndpoint: '/api/v1/systeminfo',
  },
  {
    id: 'glances',
    name: 'Glances',
    description: 'System monitoring',
    defaultSlug: 'glances',
    bundledSpec: 'glances.json',
    authType: 'none',
    urlPlaceholder: 'http://glances:61208',
    tokenLabel: 'Not required',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/glances.svg',
    color: '#4B8BBE',
    testEndpoint: '/api/4/status',
  },
  {
    id: 'ollama',
    name: 'Ollama',
    description: 'Local LLM runtime',
    defaultSlug: 'ollama',
    bundledSpec: 'ollama.json',
    authType: 'none',
    urlPlaceholder: 'http://ollama:11434',
    tokenLabel: 'Bearer Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/ollama.svg',
    color: '#8B8FA3',
    testEndpoint: '/api/tags',
  },
  {
    id: 'docker-engine',
    name: 'Docker Engine',
    description: 'Container runtime API',
    defaultSlug: 'docker-engine',
    bundledSpec: 'docker-engine.json',
    authType: 'none',
    urlPlaceholder: 'http://docker-host:2375',
    tokenLabel: 'Not required',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/docker-engine.svg',
    color: '#2496ED',
    testEndpoint: '/v1.56/_ping',
  },
  {
    id: 'traccar',
    name: 'Traccar',
    description: 'GPS tracking',
    defaultSlug: 'traccar',
    bundledSpec: 'traccar.json',
    authType: 'bearer',
    urlPlaceholder: 'http://traccar:8082',
    tokenLabel: 'API Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/traccar.svg',
    color: '#0F5C9E',
    testEndpoint: '/api/devices',
  },
  {
    id: 'grocy',
    name: 'Grocy',
    description: 'Groceries and household',
    defaultSlug: 'grocy',
    bundledSpec: 'grocy.json',
    authType: 'header',
    authHeaderName: 'GROCY-API-KEY',
    urlPlaceholder: 'http://grocy:9283',
    tokenLabel: 'API Key',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/grocy.svg',
    color: '#4C956C',
    testEndpoint: '/api/system/info',
  },
  {
    id: 'adguard-home',
    name: 'AdGuard Home',
    description: 'DNS ad blocking',
    defaultSlug: 'adguard-home',
    bundledSpec: 'adguard-home.json',
    authType: 'basic',
    urlPlaceholder: 'http://adguard:3000',
    tokenLabel: 'Password',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/adguard-home.svg',
    color: '#68BC71',
    testEndpoint: '/control/status',
  },
  {
    id: 'speedtest-tracker',
    name: 'Speedtest Tracker',
    description: 'Internet speed history',
    defaultSlug: 'speedtest-tracker',
    bundledSpec: 'speedtest-tracker.json',
    authType: 'bearer',
    urlPlaceholder: 'http://speedtest-tracker:8080',
    tokenLabel: 'API Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/ookla-speedtest.svg',
    color: '#1E88E5',
    testEndpoint: '/api/v1/results',
  },
  {
    id: 'alertmanager',
    name: 'Alertmanager',
    description: 'Prometheus alerting',
    defaultSlug: 'alertmanager',
    bundledSpec: 'alertmanager.json',
    authType: 'none',
    urlPlaceholder: 'http://alertmanager:9093',
    tokenLabel: 'Not required',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/alertmanager.svg',
    color: '#E6522C',
    testEndpoint: '/api/v2/status',
  },
  {
    id: 'authentik',
    name: 'authentik',
    description: 'Identity provider',
    defaultSlug: 'authentik',
    bundledSpec: 'authentik/2026.8.2.json',
    specVersions: [
      { value: '2026.8.2', bundledSpec: 'authentik/2026.8.2.json' },
      { value: '2025.8.4', bundledSpec: 'authentik/2025.8.4.json' },
    ],
    authType: 'bearer',
    urlPlaceholder: 'https://authentik.example.com',
    tokenLabel: 'API Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/authentik.svg',
    color: '#FD4B2D',
    testEndpoint: '/api/v3/admin/version/',
  },
  {
    id: 'gitea',
    name: 'Gitea',
    description: 'Git hosting',
    defaultSlug: 'gitea',
    bundledSpec: 'gitea.json',
    authType: 'header',
    authHeaderName: 'Authorization',
    authValuePrefix: 'token ',
    urlPlaceholder: 'http://gitea:3000',
    tokenLabel: 'Personal Access Token',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/gitea.svg',
    color: '#609926',
    testEndpoint: '/api/v1/version',
  },
  {
    id: 'frigate',
    name: 'Frigate',
    description: 'NVR with object detection',
    defaultSlug: 'frigate',
    bundledSpec: 'frigate/0.17.2.json',
    specVersions: [
      { value: '0.17.2', bundledSpec: 'frigate/0.17.2.json' },
      { value: '0.16.4', bundledSpec: 'frigate/0.16.4.json' },
      { value: '0.15.2', bundledSpec: 'frigate/0.15.2.json' },
    ],
    authType: 'none',
    urlPlaceholder: 'http://frigate:5000',
    tokenLabel: 'Not required',
    logo: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/frigate.svg',
    color: '#1F6FEB',
    testEndpoint: '/api/version',
  },
]

/** Credentials a user typed into the add/edit form, before they become an AuthConfig. */
export interface TemplateCredentials {
  token?: string
  username?: string
  password?: string
}

/**
 * The AuthConfig a template's declared auth style produces from what the user typed. Lives here
 * rather than beside the connection test because the add and edit forms call it from the browser,
 * where `test-connection.ts` (and its node:http import) must not be pulled in.
 */
export function templateAuth(template: ServiceTemplate, creds: TemplateCredentials): AuthConfig {
  switch (template.authType) {
    case 'bearer':
      return { type: 'bearer', token: creds.token || undefined }
    case 'header':
      if (!template.authHeaderName) return { type: 'none' }

      return {
        type: 'header',
        name: template.authHeaderName,
        // Some APIs want a scheme word before the secret (Gitea: `token <PAT>`). The template
        // declares it, rather than it being guessed from the header name. A blank secret stays
        // undefined so an edit means "keep the stored value" instead of saving a bare prefix.
        value: creds.token ? `${template.authValuePrefix ?? ''}${creds.token}` : undefined,
      }
    case 'basic':
      return { type: 'basic', username: creds.username || undefined, password: creds.password || undefined }
    case 'none':
    default:
      return { type: 'none' }
  }
}

export function getTemplate(id: string): ServiceTemplate | undefined {
  return templates.find((t) => t.id === id)
}

export function resolveBundledSpec(template: ServiceTemplate, version?: string): string {
  if (template.specVersions && template.specVersions.length > 0) {
    const match = template.specVersions.find((v) => v.value === version)

    return (match ?? template.specVersions[0]).bundledSpec
  }

  return template.bundledSpec
}
