/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesSlugRouteImport } from './routes/sources/$slug'
import { Route as ApiSpecRouteImport } from './routes/api/spec'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiSourcesIndexRouteImport } from './routes/api/sources/index'
import { Route as ApiSourcesSlugRouteImport } from './routes/api/sources/$slug'
import { Route as ApiProxySlugSplatRouteImport } from './routes/api/proxy/$slug/$'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSlugRoute = SourcesSlugRouteImport.update({
  id: '/sources/$slug',
  path: '/sources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpecRoute = ApiSpecRouteImport.update({
  id: '/api/spec',
  path: '/api/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourcesIndexRoute = ApiSourcesIndexRouteImport.update({
  id: '/api/sources/',
  path: '/api/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourcesSlugRoute = ApiSourcesSlugRouteImport.update({
  id: '/api/sources/$slug',
  path: '/api/sources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySlugSplatRoute = ApiProxySlugSplatRouteImport.update({
  id: '/api/proxy/$slug/$',
  path: '/api/proxy/$slug/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/spec': typeof ApiSpecRoute
  '/sources/$slug': typeof SourcesSlugRoute
  '/api/sources/$slug': typeof ApiSourcesSlugRoute
  '/api/sources/': typeof ApiSourcesIndexRoute
  '/api/proxy/$slug/$': typeof ApiProxySlugSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/spec': typeof ApiSpecRoute
  '/sources/$slug': typeof SourcesSlugRoute
  '/api/sources/$slug': typeof ApiSourcesSlugRoute
  '/api/sources': typeof ApiSourcesIndexRoute
  '/api/proxy/$slug/$': typeof ApiProxySlugSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/spec': typeof ApiSpecRoute
  '/sources/$slug': typeof SourcesSlugRoute
  '/api/sources/$slug': typeof ApiSourcesSlugRoute
  '/api/sources/': typeof ApiSourcesIndexRoute
  '/api/proxy/$slug/$': typeof ApiProxySlugSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/status'
    | '/api/mcp'
    | '/api/spec'
    | '/sources/$slug'
    | '/api/sources/$slug'
    | '/api/sources/'
    | '/api/proxy/$slug/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/status'
    | '/api/mcp'
    | '/api/spec'
    | '/sources/$slug'
    | '/api/sources/$slug'
    | '/api/sources'
    | '/api/proxy/$slug/$'
  id:
    | '__root__'
    | '/'
    | '/status'
    | '/api/mcp'
    | '/api/spec'
    | '/sources/$slug'
    | '/api/sources/$slug'
    | '/api/sources/'
    | '/api/proxy/$slug/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatusRoute: typeof StatusRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiSpecRoute: typeof ApiSpecRoute
  SourcesSlugRoute: typeof SourcesSlugRoute
  ApiSourcesSlugRoute: typeof ApiSourcesSlugRoute
  ApiSourcesIndexRoute: typeof ApiSourcesIndexRoute
  ApiProxySlugSplatRoute: typeof ApiProxySlugSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$slug': {
      id: '/sources/$slug'
      path: '/sources/$slug'
      fullPath: '/sources/$slug'
      preLoaderRoute: typeof SourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spec': {
      id: '/api/spec'
      path: '/api/spec'
      fullPath: '/api/spec'
      preLoaderRoute: typeof ApiSpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sources/': {
      id: '/api/sources/'
      path: '/api/sources'
      fullPath: '/api/sources/'
      preLoaderRoute: typeof ApiSourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sources/$slug': {
      id: '/api/sources/$slug'
      path: '/api/sources/$slug'
      fullPath: '/api/sources/$slug'
      preLoaderRoute: typeof ApiSourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$slug/$': {
      id: '/api/proxy/$slug/$'
      path: '/api/proxy/$slug/$'
      fullPath: '/api/proxy/$slug/$'
      preLoaderRoute: typeof ApiProxySlugSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatusRoute: StatusRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiSpecRoute: ApiSpecRoute,
  SourcesSlugRoute: SourcesSlugRoute,
  ApiSourcesSlugRoute: ApiSourcesSlugRoute,
  ApiSourcesIndexRoute: ApiSourcesIndexRoute,
  ApiProxySlugSplatRoute: ApiProxySlugSplatRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
