/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesSlugRouteImport } from './routes/sources/$slug'
import { Route as ApiSpecRouteImport } from './routes/api/spec'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiProxySlugSplatRouteImport } from './routes/api/proxy/$slug/$'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSlugRoute = SourcesSlugRouteImport.update({
  id: '/sources/$slug',
  path: '/sources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpecRoute = ApiSpecRouteImport.update({
  id: '/api/spec',
  path: '/api/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySlugSplatRoute = ApiProxySlugSplatRouteImport.update({
  id: '/api/proxy/$slug/$',
  path: '/api/proxy/$slug/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/api/spec': typeof ApiSpecRoute
  '/sources/$slug': typeof SourcesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/proxy/$slug/$': typeof ApiProxySlugSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/api/spec': typeof ApiSpecRoute
  '/sources/$slug': typeof SourcesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/proxy/$slug/$': typeof ApiProxySlugSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/api/spec': typeof ApiSpecRoute
  '/sources/$slug': typeof SourcesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/proxy/$slug/$': typeof ApiProxySlugSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/mcp' | '/api/spec' | '/sources/$slug' | '/api/auth/$' | '/api/proxy/$slug/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/mcp' | '/api/spec' | '/sources/$slug' | '/api/auth/$' | '/api/proxy/$slug/$'
  id: '__root__' | '/' | '/login' | '/mcp' | '/api/spec' | '/sources/$slug' | '/api/auth/$' | '/api/proxy/$slug/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ApiSpecRoute: typeof ApiSpecRoute
  SourcesSlugRoute: typeof SourcesSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProxySlugSplatRoute: typeof ApiProxySlugSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$slug': {
      id: '/sources/$slug'
      path: '/sources/$slug'
      fullPath: '/sources/$slug'
      preLoaderRoute: typeof SourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spec': {
      id: '/api/spec'
      path: '/api/spec'
      fullPath: '/api/spec'
      preLoaderRoute: typeof ApiSpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$slug/$': {
      id: '/api/proxy/$slug/$'
      path: '/api/proxy/$slug/$'
      fullPath: '/api/proxy/$slug/$'
      preLoaderRoute: typeof ApiProxySlugSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ApiSpecRoute: ApiSpecRoute,
  SourcesSlugRoute: SourcesSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProxySlugSplatRoute: ApiProxySlugSplatRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
